trigger:
- main

pool:
  name: Azure Pipelines

stages:
# 🔨 Build Stage
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
        npm test
      displayName: 'npm install, build and test'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
      displayName: 'Publish test results'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Create archive file'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish build artifacts'

# 🚀 Deploy Stage
- stage: Deploy
  displayName: 'Deploy to App Service'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to App Service'
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Artifacts'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'ARM-connection-Andrewogunbayo'   # 🔁 Replace with your actual service connection name
        appType: 'webApp'
        appName: 'Lab6andrew'                       # 🔁 Replace with your actual App Service name
        package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
      displayName: 'Deploy to App Service'